version: '3.9'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - MyAPP.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      - "8000:8080"
    restart: always

    env_file:
      - .env

    volumes:
      - ./MyAPP/database:/app/database

    logging:
      driver: loki
      options:
       loki-url: 'http://localhost:3100/loki/api/v1/push'


  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'
