# Generated by Django 5.0 on 2023-12-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopppCat', '0002_product_createt_at_product_discount_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arhivate',
            field=models.BooleanField(default=False),
        ),
    ]
