# Generated by Django 5.0 on 2023-12-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopppCat', '0003_product_arhivate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=100, null=True)),
                ('createt_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
