# Generated by Django 5.0.2 on 2024-03-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopppCat', '0008_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
